---
deployment:
  tasks:
    - /bin/cp -Rf * /home/libp7469/libertamedia/
    - /bin/cp -f dist/index.html /home/libp7469/public_html/index.html
    - /bin/mkdir -p /home/libp7469/public_html/assets
    - /bin/cp -Rf dist/assets/* /home/libp7469/public_html/assets/
    - /bin/mkdir -p /home/libp7469/libertamedia/tmp
    - /bin/touch /home/libp7469/libertamedia/tmp/restart.txt
