import React, { useState } from 'react';
import { X, Send, CheckCircle2 } from 'lucide-react';
import { CategoryType, CitizenSubmission } from '../types';
import { api } from '../services/api';

interface SubmitStoryModalProps { isOpen:boolean; onClose:()=>void; onSubmit?:(submission:CitizenSubmission)=>void; }

export function normalizeCitizenSubmission(formData:{title:string;category:CategoryType;authorName:string;email:string;institution?:string;abstract?:string;content:string}):Omit<CitizenSubmission,'id'|'submittedAt'>{
  return { title:formData.title.trim(), category:formData.category, authorName:formData.authorName.trim(), authorEmail:formData.email.trim(), authorOrg:formData.institution?.trim()||undefined, content:`${formData.abstract?.trim()?formData.abstract.trim()+'\n\n':''}${formData.content.trim()}` };
}

export const SubmitStoryModal:React.FC<SubmitStoryModalProps>=({isOpen,onClose,onSubmit})=>{
  const [form,setForm]=useState({title:'',category:'Opini' as CategoryType,authorName:'',email:'',institution:'',abstract:'',content:''});
  const [loading,setLoading]=useState(false); const [submitted,setSubmitted]=useState(false);
  if(!isOpen)return null;
  const reset=()=>{setForm({title:'',category:'Opini',authorName:'',email:'',institution:'',abstract:'',content:''});setSubmitted(false);onClose();};
  const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!form.title.trim()||!form.authorName.trim()||!form.email.trim()||!form.content.trim())return;setLoading(true);try{const submission=await api.submitCitizenStory(normalizeCitizenSubmission(form));onSubmit?.(submission);setSubmitted(true);}catch(err:any){alert(err?.message||'Gagal mengirim naskah.')}finally{setLoading(false);}};
  return <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-sm flex items-center justify-center p-4"><div className="bg-white rounded-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto shadow-2xl"><div className="bg-[#E5252A] text-white p-5 flex justify-between items-center"><div><h3 className="font-black">Kirim Tulisan & Opini Pembaca</h3><p className="text-xs text-red-100">Kanal Partisipasi Publik libertamedia</p></div><button onClick={reset}><X className="w-5 h-5"/></button></div>{submitted?<div className="p-10 text-center"><CheckCircle2 className="w-14 h-14 text-emerald-500 mx-auto mb-4"/><h4 className="text-xl font-black">Naskah berhasil terkirim</h4><p className="text-sm text-slate-600 mt-2">Dewan Redaksi LIBERTAMEDIA akan meninjau naskah Anda.</p><button onClick={reset} className="mt-6 bg-[#E5252A] text-white px-5 py-2 rounded-lg text-sm font-bold">Kembali</button></div>:<form onSubmit={submit} className="p-6 space-y-4"><div className="grid sm:grid-cols-2 gap-3"><input required placeholder="Nama lengkap" value={form.authorName} onChange={e=>setForm({...form,authorName:e.target.value})} className="border rounded-lg p-3 text-sm"/><input required type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="border rounded-lg p-3 text-sm"/></div><div className="grid sm:grid-cols-2 gap-3"><select value={form.category} onChange={e=>setForm({...form,category:e.target.value as CategoryType})} className="border rounded-lg p-3 text-sm"><option>Opini</option><option>Gagasan</option><option>Cerita Inspiratif</option><option>Mahasiswa</option><option>Sosial Budaya</option></select><input placeholder="Institusi / komunitas / kota" value={form.institution} onChange={e=>setForm({...form,institution:e.target.value})} className="border rounded-lg p-3 text-sm"/></div><input required placeholder="Judul tulisan" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="w-full border rounded-lg p-3 text-sm"/><input placeholder="Abstrak singkat" value={form.abstract} onChange={e=>setForm({...form,abstract:e.target.value})} className="w-full border rounded-lg p-3 text-sm"/><textarea required rows={10} placeholder="Isi naskah" value={form.content} onChange={e=>setForm({...form,content:e.target.value})} className="w-full border rounded-lg p-3 text-sm"/><div className="flex justify-end gap-3"><button type="button" onClick={reset} className="px-4 py-2 text-sm">Batal</button><button disabled={loading} className="bg-[#E5252A] text-white px-5 py-2.5 rounded-lg font-bold text-sm flex items-center gap-2"><Send className="w-4 h-4"/>{loading?'Mengirim...':'Kirim Naskah'}</button></div></form>}</div></div>;
};