export type CategoryType='Semua'|'Pemerintahan'|'Politik'|'Mahasiswa'|'Sosial Budaya'|'Ekonomi'|'Olahraga & Seni'|'Organisasi & Komunitas'|'Opini'|'Gagasan'|'Cerita Inspiratif'|'Internasional';
export interface Author{name:string;avatar:string;role?:string;organization?:string;institution?:string;email?:string}
export interface Article{id:string;title:string;slug:string;excerpt:string;content:string;category:CategoryType;pillar?:'BERITA'|'OPINI'|'CERITA'|'GAGASAN'|string;subcategory?:string;summary?:string;imageUrl:string;image?:string;imageCaption?:string;caption?:string;author:Author;publishedAt:string;readTime:string;isHeroHeadline?:boolean;isHero?:boolean;isEditorsPick?:boolean;isEditorChoice?:boolean;isTrending?:boolean;views?:number;tags?:string[];commentsCount?:number;status?:'PUBLISHED'|'DRAFT'|'ARCHIVED'|'REVIEW'|'FACT_CHECK'|'APPROVED'|'SCHEDULED';audioUrl?:string}
export interface Comment{id:string;articleId?:string;author:string;avatar?:string;content:string;createdAt?:string;date?:string;likes?:number}
export type CommentItem=Comment;
export interface VideoItem{id:string;title:string;youtubeId:string;category:CategoryType;duration:string;publishedAt:string;views:number}
export interface PollOption{id:string;text:string;votes:number}
export interface PollData{id:string;question:string;options:PollOption[];totalVotes:number;topic?:string;endDate?:string}
export interface CitizenSubmission{id:string;authorName:string;authorEmail?:string;authorRole?:string;authorOrg?:string;email?:string;institution?:string;abstract?:string;title:string;category:CategoryType;content:string;submittedAt:string;[key:string]:unknown}
export type Submission=CitizenSubmission;
export interface SiteSettings{siteName:string;siteTagline:string;footerText:string;logoUrl?:string;customCategories?:CategoryType[];socialLinks:{instagram:string;twitter:string;youtube:string;facebook:string};sections:{showBreakingNews:boolean;showHeroSlider:boolean;showEditorChoice:boolean;showCitizenVoice:boolean;showNewsletter:boolean};monetization:{headerBannerHtml:string;inArticleAdHtml:string;googleAnalyticsId:string}}
export interface StaticPage{id:string;slug:string;title:string;content:string;updatedAt:string}